### ISSUE TITLE
Single Trip calendar throws date errors sometimes. Debug

### ISSUE THREAD

**Issue by jmartin-code** [2107-Capstone/capstone#155]
![image](https://user-images.githubusercontent.com/68358371/145938727-6eb005a4-2fc9-46e6-a2ce-fb4b8b00ce46.png)

When user go from alltrips and click on a trip. Then in the single trip clicks on the calendar. Sometimes the singletrip calendar throws an date error.

**Comment by nightsandwich** [comment]
was using startTime instead of start
